### ISSUE TITLE
Pioneer causing java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512

### ISSUE THREAD

**Issue by Malefic007** [OrderedChaos-Dev/Pioneer#2]
After running a world for over 800+ days in a mod called Life in The Villlage 3 that utilizes Pioneer mod, they have all ended up with the error: java.lang.RuntimeException: Tried to read NBT tag with too high complexity, depth > 512 in the log when the load fails.  The error received in game when this occurs is: 
![image](https://user-images.githubusercontent.com/130177657/230658116-cc361439-c775-4ef3-83d8-6a2328c1168a.png)

I was able to troubleshoot the issue by finding a backup that has a level.dat that works.  The weird thing that has happened on these worlds is that even with a index.dat that works if I play for a bit or even immediately log back off when I load back in the above error will appear until I again drop a the working level.dat file over the now bad one.  I never crash in game only on the initial save loading, so for as long as I play that instance I can play just fine until I log out of the game, so of course I lose a lot of progress in a perpetual ground hog day.

Because I can make it work for one run with a working backup, I was able to pinpoint Pioneer and a work around for it after literally disabling all my mods and restoring my save with a working level.dat while slowly adding mods back in (and of course restoring my save each time so all the information was available) until I got it to the one mod that caused the issue.

I found a work around by loading the game with a restored save and a working index.dat without Pioneer then logging back out.  After that if I re-enable (or not re-enable) the Pioneer mod, the game loads just fine again probably because whatever caused the NBT issue was removed (at least for now as I assume it will eventually come back again because I like my Baobob trees!).

I provided a log with the error as an attachment.

[2023-04-05-6.log](https://github.com/OrderedChaos-Dev/Pioneer/files/11180741/2023-04-05-6.log)

**Comment by OrderedChaos-Dev** [comment]
Hi, apologies for the late reply. I did see this a year ago but this coincided with my wedding so I lost track. This probably doesn't help anymore, but fwiw this is more likely caused by something else I think? Pioneer doesn't modify or store any NBT data, and typically the too high complexity is caused by nested data in NBT storage.
